// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AuditAssetReader is a Reader for the AuditAsset structure.
type AuditAssetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AuditAssetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAuditAssetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewAuditAssetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 502:
		result := NewAuditAssetBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAuditAssetOK creates a AuditAssetOK with default headers values
func NewAuditAssetOK() *AuditAssetOK {
	return &AuditAssetOK{}
}

/* AuditAssetOK describes a response with status code 200, with default header values.

Asset Audit Trail has been retrieved and is in the body
*/
type AuditAssetOK struct {
}

func (o *AuditAssetOK) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan/{channelID}/asset/{assetID}/trail][%d] auditAssetOK ", 200)
}

func (o *AuditAssetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAuditAssetNotFound creates a AuditAssetNotFound with default headers values
func NewAuditAssetNotFound() *AuditAssetNotFound {
	return &AuditAssetNotFound{}
}

/* AuditAssetNotFound describes a response with status code 404, with default header values.

No channel, repository or asset found for that URI
*/
type AuditAssetNotFound struct {
}

func (o *AuditAssetNotFound) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan/{channelID}/asset/{assetID}/trail][%d] auditAssetNotFound ", 404)
}

func (o *AuditAssetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAuditAssetBadGateway creates a AuditAssetBadGateway with default headers values
func NewAuditAssetBadGateway() *AuditAssetBadGateway {
	return &AuditAssetBadGateway{}
}

/* AuditAssetBadGateway describes a response with status code 502, with default header values.

Error on repository agent
*/
type AuditAssetBadGateway struct {
}

func (o *AuditAssetBadGateway) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan/{channelID}/asset/{assetID}/trail][%d] auditAssetBadGateway ", 502)
}

func (o *AuditAssetBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
