// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAuditAssetParams creates a new AuditAssetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAuditAssetParams() *AuditAssetParams {
	return &AuditAssetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAuditAssetParamsWithTimeout creates a new AuditAssetParams object
// with the ability to set a timeout on a request.
func NewAuditAssetParamsWithTimeout(timeout time.Duration) *AuditAssetParams {
	return &AuditAssetParams{
		timeout: timeout,
	}
}

// NewAuditAssetParamsWithContext creates a new AuditAssetParams object
// with the ability to set a context for a request.
func NewAuditAssetParamsWithContext(ctx context.Context) *AuditAssetParams {
	return &AuditAssetParams{
		Context: ctx,
	}
}

// NewAuditAssetParamsWithHTTPClient creates a new AuditAssetParams object
// with the ability to set a custom HTTPClient for a request.
func NewAuditAssetParamsWithHTTPClient(client *http.Client) *AuditAssetParams {
	return &AuditAssetParams{
		HTTPClient: client,
	}
}

/* AuditAssetParams contains all the parameters to send to the API endpoint
   for the audit asset operation.

   Typically these are written to a http.Request.
*/
type AuditAssetParams struct {

	/* AssetID.

	   Asset ID
	*/
	AssetID string

	/* ChannelID.

	   Channel ID
	*/
	ChannelID string

	/* RepoID.

	   Repository ID
	*/
	RepoID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the audit asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuditAssetParams) WithDefaults() *AuditAssetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the audit asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuditAssetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the audit asset params
func (o *AuditAssetParams) WithTimeout(timeout time.Duration) *AuditAssetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the audit asset params
func (o *AuditAssetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the audit asset params
func (o *AuditAssetParams) WithContext(ctx context.Context) *AuditAssetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the audit asset params
func (o *AuditAssetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the audit asset params
func (o *AuditAssetParams) WithHTTPClient(client *http.Client) *AuditAssetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the audit asset params
func (o *AuditAssetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAssetID adds the assetID to the audit asset params
func (o *AuditAssetParams) WithAssetID(assetID string) *AuditAssetParams {
	o.SetAssetID(assetID)
	return o
}

// SetAssetID adds the assetId to the audit asset params
func (o *AuditAssetParams) SetAssetID(assetID string) {
	o.AssetID = assetID
}

// WithChannelID adds the channelID to the audit asset params
func (o *AuditAssetParams) WithChannelID(channelID string) *AuditAssetParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the audit asset params
func (o *AuditAssetParams) SetChannelID(channelID string) {
	o.ChannelID = channelID
}

// WithRepoID adds the repoID to the audit asset params
func (o *AuditAssetParams) WithRepoID(repoID string) *AuditAssetParams {
	o.SetRepoID(repoID)
	return o
}

// SetRepoID adds the repoId to the audit asset params
func (o *AuditAssetParams) SetRepoID(repoID string) {
	o.RepoID = repoID
}

// WriteToRequest writes these params to a swagger request
func (o *AuditAssetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param assetID
	if err := r.SetPathParam("assetID", o.AssetID); err != nil {
		return err
	}

	// path param channelID
	if err := r.SetPathParam("channelID", o.ChannelID); err != nil {
		return err
	}

	// path param repoID
	if err := r.SetPathParam("repoID", o.RepoID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
