// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExportFileAssetParams creates a new ExportFileAssetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExportFileAssetParams() *ExportFileAssetParams {
	return &ExportFileAssetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExportFileAssetParamsWithTimeout creates a new ExportFileAssetParams object
// with the ability to set a timeout on a request.
func NewExportFileAssetParamsWithTimeout(timeout time.Duration) *ExportFileAssetParams {
	return &ExportFileAssetParams{
		timeout: timeout,
	}
}

// NewExportFileAssetParamsWithContext creates a new ExportFileAssetParams object
// with the ability to set a context for a request.
func NewExportFileAssetParamsWithContext(ctx context.Context) *ExportFileAssetParams {
	return &ExportFileAssetParams{
		Context: ctx,
	}
}

// NewExportFileAssetParamsWithHTTPClient creates a new ExportFileAssetParams object
// with the ability to set a custom HTTPClient for a request.
func NewExportFileAssetParamsWithHTTPClient(client *http.Client) *ExportFileAssetParams {
	return &ExportFileAssetParams{
		HTTPClient: client,
	}
}

/* ExportFileAssetParams contains all the parameters to send to the API endpoint
   for the export file asset operation.

   Typically these are written to a http.Request.
*/
type ExportFileAssetParams struct {

	/* AssetID.

	   Asset ID
	*/
	AssetID string

	/* ChannelID.

	   Channel ID
	*/
	ChannelID string

	/* FileName.

	   Name of file to export
	*/
	FileName string

	/* RepoID.

	   Repository ID
	*/
	RepoID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the export file asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExportFileAssetParams) WithDefaults() *ExportFileAssetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the export file asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExportFileAssetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the export file asset params
func (o *ExportFileAssetParams) WithTimeout(timeout time.Duration) *ExportFileAssetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the export file asset params
func (o *ExportFileAssetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the export file asset params
func (o *ExportFileAssetParams) WithContext(ctx context.Context) *ExportFileAssetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the export file asset params
func (o *ExportFileAssetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the export file asset params
func (o *ExportFileAssetParams) WithHTTPClient(client *http.Client) *ExportFileAssetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the export file asset params
func (o *ExportFileAssetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAssetID adds the assetID to the export file asset params
func (o *ExportFileAssetParams) WithAssetID(assetID string) *ExportFileAssetParams {
	o.SetAssetID(assetID)
	return o
}

// SetAssetID adds the assetId to the export file asset params
func (o *ExportFileAssetParams) SetAssetID(assetID string) {
	o.AssetID = assetID
}

// WithChannelID adds the channelID to the export file asset params
func (o *ExportFileAssetParams) WithChannelID(channelID string) *ExportFileAssetParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the export file asset params
func (o *ExportFileAssetParams) SetChannelID(channelID string) {
	o.ChannelID = channelID
}

// WithFileName adds the fileName to the export file asset params
func (o *ExportFileAssetParams) WithFileName(fileName string) *ExportFileAssetParams {
	o.SetFileName(fileName)
	return o
}

// SetFileName adds the fileName to the export file asset params
func (o *ExportFileAssetParams) SetFileName(fileName string) {
	o.FileName = fileName
}

// WithRepoID adds the repoID to the export file asset params
func (o *ExportFileAssetParams) WithRepoID(repoID string) *ExportFileAssetParams {
	o.SetRepoID(repoID)
	return o
}

// SetRepoID adds the repoId to the export file asset params
func (o *ExportFileAssetParams) SetRepoID(repoID string) {
	o.RepoID = repoID
}

// WriteToRequest writes these params to a swagger request
func (o *ExportFileAssetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param assetID
	if err := r.SetPathParam("assetID", o.AssetID); err != nil {
		return err
	}

	// path param channelID
	if err := r.SetPathParam("channelID", o.ChannelID); err != nil {
		return err
	}

	// path param fileName
	if err := r.SetPathParam("fileName", o.FileName); err != nil {
		return err
	}

	// path param repoID
	if err := r.SetPathParam("repoID", o.RepoID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
