// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExportFileAssetReader is a Reader for the ExportFileAsset structure.
type ExportFileAssetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExportFileAssetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExportFileAssetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewExportFileAssetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 502:
		result := NewExportFileAssetBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExportFileAssetOK creates a ExportFileAssetOK with default headers values
func NewExportFileAssetOK() *ExportFileAssetOK {
	return &ExportFileAssetOK{}
}

/* ExportFileAssetOK describes a response with status code 200, with default header values.

Asset as been exported to a json tree available in the filename specified
*/
type ExportFileAssetOK struct {
}

func (o *ExportFileAssetOK) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan/{channelID}/asset/{assetID}/export/{fileName}][%d] exportFileAssetOK ", 200)
}

func (o *ExportFileAssetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExportFileAssetNotFound creates a ExportFileAssetNotFound with default headers values
func NewExportFileAssetNotFound() *ExportFileAssetNotFound {
	return &ExportFileAssetNotFound{}
}

/* ExportFileAssetNotFound describes a response with status code 404, with default header values.

No channel, repository or asset found for that URI
*/
type ExportFileAssetNotFound struct {
}

func (o *ExportFileAssetNotFound) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan/{channelID}/asset/{assetID}/export/{fileName}][%d] exportFileAssetNotFound ", 404)
}

func (o *ExportFileAssetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExportFileAssetBadGateway creates a ExportFileAssetBadGateway with default headers values
func NewExportFileAssetBadGateway() *ExportFileAssetBadGateway {
	return &ExportFileAssetBadGateway{}
}

/* ExportFileAssetBadGateway describes a response with status code 502, with default header values.

Error on repository agent
*/
type ExportFileAssetBadGateway struct {
}

func (o *ExportFileAssetBadGateway) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan/{channelID}/asset/{assetID}/export/{fileName}][%d] exportFileAssetBadGateway ", 502)
}

func (o *ExportFileAssetBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
