// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExportAssetReader is a Reader for the ExportAsset structure.
type ExportAssetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExportAssetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExportAssetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewExportAssetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 502:
		result := NewExportAssetBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExportAssetOK creates a ExportAssetOK with default headers values
func NewExportAssetOK() *ExportAssetOK {
	return &ExportAssetOK{}
}

/* ExportAssetOK describes a response with status code 200, with default header values.

Asset as been exported to a json tree available in the body
*/
type ExportAssetOK struct {
}

func (o *ExportAssetOK) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan/{channelID}/asset/{assetID}/export][%d] exportAssetOK ", 200)
}

func (o *ExportAssetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExportAssetNotFound creates a ExportAssetNotFound with default headers values
func NewExportAssetNotFound() *ExportAssetNotFound {
	return &ExportAssetNotFound{}
}

/* ExportAssetNotFound describes a response with status code 404, with default header values.

No channel, repository or asset found for that URI
*/
type ExportAssetNotFound struct {
}

func (o *ExportAssetNotFound) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan/{channelID}/asset/{assetID}/export][%d] exportAssetNotFound ", 404)
}

func (o *ExportAssetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExportAssetBadGateway creates a ExportAssetBadGateway with default headers values
func NewExportAssetBadGateway() *ExportAssetBadGateway {
	return &ExportAssetBadGateway{}
}

/* ExportAssetBadGateway describes a response with status code 502, with default header values.

Error on repository agent
*/
type ExportAssetBadGateway struct {
}

func (o *ExportAssetBadGateway) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan/{channelID}/asset/{assetID}/export][%d] exportAssetBadGateway ", 502)
}

func (o *ExportAssetBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
