// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExportAssetParams creates a new ExportAssetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExportAssetParams() *ExportAssetParams {
	return &ExportAssetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExportAssetParamsWithTimeout creates a new ExportAssetParams object
// with the ability to set a timeout on a request.
func NewExportAssetParamsWithTimeout(timeout time.Duration) *ExportAssetParams {
	return &ExportAssetParams{
		timeout: timeout,
	}
}

// NewExportAssetParamsWithContext creates a new ExportAssetParams object
// with the ability to set a context for a request.
func NewExportAssetParamsWithContext(ctx context.Context) *ExportAssetParams {
	return &ExportAssetParams{
		Context: ctx,
	}
}

// NewExportAssetParamsWithHTTPClient creates a new ExportAssetParams object
// with the ability to set a custom HTTPClient for a request.
func NewExportAssetParamsWithHTTPClient(client *http.Client) *ExportAssetParams {
	return &ExportAssetParams{
		HTTPClient: client,
	}
}

/* ExportAssetParams contains all the parameters to send to the API endpoint
   for the export asset operation.

   Typically these are written to a http.Request.
*/
type ExportAssetParams struct {

	/* AssetID.

	   Asset ID
	*/
	AssetID string

	/* ChannelID.

	   Channel ID
	*/
	ChannelID string

	/* InlineOutput.

	   Output as inline json
	*/
	InlineOutput *string

	/* RepoID.

	   Repository ID
	*/
	RepoID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the export asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExportAssetParams) WithDefaults() *ExportAssetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the export asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExportAssetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the export asset params
func (o *ExportAssetParams) WithTimeout(timeout time.Duration) *ExportAssetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the export asset params
func (o *ExportAssetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the export asset params
func (o *ExportAssetParams) WithContext(ctx context.Context) *ExportAssetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the export asset params
func (o *ExportAssetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the export asset params
func (o *ExportAssetParams) WithHTTPClient(client *http.Client) *ExportAssetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the export asset params
func (o *ExportAssetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAssetID adds the assetID to the export asset params
func (o *ExportAssetParams) WithAssetID(assetID string) *ExportAssetParams {
	o.SetAssetID(assetID)
	return o
}

// SetAssetID adds the assetId to the export asset params
func (o *ExportAssetParams) SetAssetID(assetID string) {
	o.AssetID = assetID
}

// WithChannelID adds the channelID to the export asset params
func (o *ExportAssetParams) WithChannelID(channelID string) *ExportAssetParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the export asset params
func (o *ExportAssetParams) SetChannelID(channelID string) {
	o.ChannelID = channelID
}

// WithInlineOutput adds the inlineOutput to the export asset params
func (o *ExportAssetParams) WithInlineOutput(inlineOutput *string) *ExportAssetParams {
	o.SetInlineOutput(inlineOutput)
	return o
}

// SetInlineOutput adds the inlineOutput to the export asset params
func (o *ExportAssetParams) SetInlineOutput(inlineOutput *string) {
	o.InlineOutput = inlineOutput
}

// WithRepoID adds the repoID to the export asset params
func (o *ExportAssetParams) WithRepoID(repoID string) *ExportAssetParams {
	o.SetRepoID(repoID)
	return o
}

// SetRepoID adds the repoId to the export asset params
func (o *ExportAssetParams) SetRepoID(repoID string) {
	o.RepoID = repoID
}

// WriteToRequest writes these params to a swagger request
func (o *ExportAssetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param assetID
	if err := r.SetPathParam("assetID", o.AssetID); err != nil {
		return err
	}

	// path param channelID
	if err := r.SetPathParam("channelID", o.ChannelID); err != nil {
		return err
	}

	if o.InlineOutput != nil {

		// query param inlineOutput
		var qrInlineOutput string

		if o.InlineOutput != nil {
			qrInlineOutput = *o.InlineOutput
		}
		qInlineOutput := qrInlineOutput
		if qInlineOutput != "" {

			if err := r.SetQueryParam("inlineOutput", qInlineOutput); err != nil {
				return err
			}
		}
	}

	// path param repoID
	if err := r.SetPathParam("repoID", o.RepoID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
