// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetChannelsReader is a Reader for the GetChannels structure.
type GetChannelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetChannelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetChannelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetChannelsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 502:
		result := NewGetChannelsBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetChannelsOK creates a GetChannelsOK with default headers values
func NewGetChannelsOK() *GetChannelsOK {
	return &GetChannelsOK{}
}

/* GetChannelsOK describes a response with status code 200, with default header values.

Array of channel ids have been retrieved and are in the body
*/
type GetChannelsOK struct {
}

func (o *GetChannelsOK) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan][%d] getChannelsOK ", 200)
}

func (o *GetChannelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetChannelsNotFound creates a GetChannelsNotFound with default headers values
func NewGetChannelsNotFound() *GetChannelsNotFound {
	return &GetChannelsNotFound{}
}

/* GetChannelsNotFound describes a response with status code 404, with default header values.

No channel, repository or asset found for that URI
*/
type GetChannelsNotFound struct {
}

func (o *GetChannelsNotFound) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan][%d] getChannelsNotFound ", 404)
}

func (o *GetChannelsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetChannelsBadGateway creates a GetChannelsBadGateway with default headers values
func NewGetChannelsBadGateway() *GetChannelsBadGateway {
	return &GetChannelsBadGateway{}
}

/* GetChannelsBadGateway describes a response with status code 502, with default header values.

Error on repository agent
*/
type GetChannelsBadGateway struct {
}

func (o *GetChannelsBadGateway) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan][%d] getChannelsBadGateway ", 502)
}

func (o *GetChannelsBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
