// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// QueryAssetsReader is a Reader for the QueryAssets structure.
type QueryAssetsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryAssetsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewQueryAssetsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewQueryAssetsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewQueryAssetsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 502:
		result := NewQueryAssetsBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewQueryAssetsOK creates a QueryAssetsOK with default headers values
func NewQueryAssetsOK() *QueryAssetsOK {
	return &QueryAssetsOK{}
}

/* QueryAssetsOK describes a response with status code 200, with default header values.

Assets have been retrieved successfully and are in the body
*/
type QueryAssetsOK struct {
	Payload interface{}
}

func (o *QueryAssetsOK) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan/{channelID}/asset/_query][%d] queryAssetsOK  %+v", 200, o.Payload)
}
func (o *QueryAssetsOK) GetPayload() interface{} {
	return o.Payload
}

func (o *QueryAssetsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryAssetsNotFound creates a QueryAssetsNotFound with default headers values
func NewQueryAssetsNotFound() *QueryAssetsNotFound {
	return &QueryAssetsNotFound{}
}

/* QueryAssetsNotFound describes a response with status code 404, with default header values.

No channel, repository or asset found for that URI
*/
type QueryAssetsNotFound struct {
}

func (o *QueryAssetsNotFound) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan/{channelID}/asset/_query][%d] queryAssetsNotFound ", 404)
}

func (o *QueryAssetsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewQueryAssetsInternalServerError creates a QueryAssetsInternalServerError with default headers values
func NewQueryAssetsInternalServerError() *QueryAssetsInternalServerError {
	return &QueryAssetsInternalServerError{}
}

/* QueryAssetsInternalServerError describes a response with status code 500, with default header values.

Error on agent
*/
type QueryAssetsInternalServerError struct {
}

func (o *QueryAssetsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan/{channelID}/asset/_query][%d] queryAssetsInternalServerError ", 500)
}

func (o *QueryAssetsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewQueryAssetsBadGateway creates a QueryAssetsBadGateway with default headers values
func NewQueryAssetsBadGateway() *QueryAssetsBadGateway {
	return &QueryAssetsBadGateway{}
}

/* QueryAssetsBadGateway describes a response with status code 502, with default header values.

Error on repository agent
*/
type QueryAssetsBadGateway struct {
}

func (o *QueryAssetsBadGateway) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan/{channelID}/asset/_query][%d] queryAssetsBadGateway ", 502)
}

func (o *QueryAssetsBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
