// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// QueryAssetsPostReader is a Reader for the QueryAssetsPost structure.
type QueryAssetsPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryAssetsPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewQueryAssetsPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewQueryAssetsPostNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewQueryAssetsPostInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 502:
		result := NewQueryAssetsPostBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewQueryAssetsPostOK creates a QueryAssetsPostOK with default headers values
func NewQueryAssetsPostOK() *QueryAssetsPostOK {
	return &QueryAssetsPostOK{}
}

/* QueryAssetsPostOK describes a response with status code 200, with default header values.

Assets have been retrieved successfully and are in the body
*/
type QueryAssetsPostOK struct {
	Payload interface{}
}

func (o *QueryAssetsPostOK) Error() string {
	return fmt.Sprintf("[POST /repo/{repoID}/chan/{channelID}/asset/_query][%d] queryAssetsPostOK  %+v", 200, o.Payload)
}
func (o *QueryAssetsPostOK) GetPayload() interface{} {
	return o.Payload
}

func (o *QueryAssetsPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryAssetsPostNotFound creates a QueryAssetsPostNotFound with default headers values
func NewQueryAssetsPostNotFound() *QueryAssetsPostNotFound {
	return &QueryAssetsPostNotFound{}
}

/* QueryAssetsPostNotFound describes a response with status code 404, with default header values.

No channel, repository or asset found for that URI
*/
type QueryAssetsPostNotFound struct {
}

func (o *QueryAssetsPostNotFound) Error() string {
	return fmt.Sprintf("[POST /repo/{repoID}/chan/{channelID}/asset/_query][%d] queryAssetsPostNotFound ", 404)
}

func (o *QueryAssetsPostNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewQueryAssetsPostInternalServerError creates a QueryAssetsPostInternalServerError with default headers values
func NewQueryAssetsPostInternalServerError() *QueryAssetsPostInternalServerError {
	return &QueryAssetsPostInternalServerError{}
}

/* QueryAssetsPostInternalServerError describes a response with status code 500, with default header values.

Error on agent
*/
type QueryAssetsPostInternalServerError struct {
}

func (o *QueryAssetsPostInternalServerError) Error() string {
	return fmt.Sprintf("[POST /repo/{repoID}/chan/{channelID}/asset/_query][%d] queryAssetsPostInternalServerError ", 500)
}

func (o *QueryAssetsPostInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewQueryAssetsPostBadGateway creates a QueryAssetsPostBadGateway with default headers values
func NewQueryAssetsPostBadGateway() *QueryAssetsPostBadGateway {
	return &QueryAssetsPostBadGateway{}
}

/* QueryAssetsPostBadGateway describes a response with status code 502, with default header values.

Error on repository agent
*/
type QueryAssetsPostBadGateway struct {
}

func (o *QueryAssetsPostBadGateway) Error() string {
	return fmt.Sprintf("[POST /repo/{repoID}/chan/{channelID}/asset/_query][%d] queryAssetsPostBadGateway ", 502)
}

func (o *QueryAssetsPostBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
