// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"dbom-grafeas/dbom/models"
)

// NewQueryAssetsPostParams creates a new QueryAssetsPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQueryAssetsPostParams() *QueryAssetsPostParams {
	return &QueryAssetsPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQueryAssetsPostParamsWithTimeout creates a new QueryAssetsPostParams object
// with the ability to set a timeout on a request.
func NewQueryAssetsPostParamsWithTimeout(timeout time.Duration) *QueryAssetsPostParams {
	return &QueryAssetsPostParams{
		timeout: timeout,
	}
}

// NewQueryAssetsPostParamsWithContext creates a new QueryAssetsPostParams object
// with the ability to set a context for a request.
func NewQueryAssetsPostParamsWithContext(ctx context.Context) *QueryAssetsPostParams {
	return &QueryAssetsPostParams{
		Context: ctx,
	}
}

// NewQueryAssetsPostParamsWithHTTPClient creates a new QueryAssetsPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewQueryAssetsPostParamsWithHTTPClient(client *http.Client) *QueryAssetsPostParams {
	return &QueryAssetsPostParams{
		HTTPClient: client,
	}
}

/* QueryAssetsPostParams contains all the parameters to send to the API endpoint
   for the query assets post operation.

   Typically these are written to a http.Request.
*/
type QueryAssetsPostParams struct {

	// Body.
	Body *models.QueryAssetDefinition

	/* ChannelID.

	   Channel ID
	*/
	ChannelID string

	/* RepoID.

	   Repository ID
	*/
	RepoID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the query assets post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryAssetsPostParams) WithDefaults() *QueryAssetsPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the query assets post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryAssetsPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the query assets post params
func (o *QueryAssetsPostParams) WithTimeout(timeout time.Duration) *QueryAssetsPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the query assets post params
func (o *QueryAssetsPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the query assets post params
func (o *QueryAssetsPostParams) WithContext(ctx context.Context) *QueryAssetsPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the query assets post params
func (o *QueryAssetsPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the query assets post params
func (o *QueryAssetsPostParams) WithHTTPClient(client *http.Client) *QueryAssetsPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the query assets post params
func (o *QueryAssetsPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the query assets post params
func (o *QueryAssetsPostParams) WithBody(body *models.QueryAssetDefinition) *QueryAssetsPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the query assets post params
func (o *QueryAssetsPostParams) SetBody(body *models.QueryAssetDefinition) {
	o.Body = body
}

// WithChannelID adds the channelID to the query assets post params
func (o *QueryAssetsPostParams) WithChannelID(channelID string) *QueryAssetsPostParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the query assets post params
func (o *QueryAssetsPostParams) SetChannelID(channelID string) {
	o.ChannelID = channelID
}

// WithRepoID adds the repoID to the query assets post params
func (o *QueryAssetsPostParams) WithRepoID(repoID string) *QueryAssetsPostParams {
	o.SetRepoID(repoID)
	return o
}

// SetRepoID adds the repoId to the query assets post params
func (o *QueryAssetsPostParams) SetRepoID(repoID string) {
	o.RepoID = repoID
}

// WriteToRequest writes these params to a swagger request
func (o *QueryAssetsPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param channelID
	if err := r.SetPathParam("channelID", o.ChannelID); err != nil {
		return err
	}

	// path param repoID
	if err := r.SetPathParam("repoID", o.RepoID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
