// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRetrieveAssetsParams creates a new RetrieveAssetsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRetrieveAssetsParams() *RetrieveAssetsParams {
	return &RetrieveAssetsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRetrieveAssetsParamsWithTimeout creates a new RetrieveAssetsParams object
// with the ability to set a timeout on a request.
func NewRetrieveAssetsParamsWithTimeout(timeout time.Duration) *RetrieveAssetsParams {
	return &RetrieveAssetsParams{
		timeout: timeout,
	}
}

// NewRetrieveAssetsParamsWithContext creates a new RetrieveAssetsParams object
// with the ability to set a context for a request.
func NewRetrieveAssetsParamsWithContext(ctx context.Context) *RetrieveAssetsParams {
	return &RetrieveAssetsParams{
		Context: ctx,
	}
}

// NewRetrieveAssetsParamsWithHTTPClient creates a new RetrieveAssetsParams object
// with the ability to set a custom HTTPClient for a request.
func NewRetrieveAssetsParamsWithHTTPClient(client *http.Client) *RetrieveAssetsParams {
	return &RetrieveAssetsParams{
		HTTPClient: client,
	}
}

/* RetrieveAssetsParams contains all the parameters to send to the API endpoint
   for the retrieve assets operation.

   Typically these are written to a http.Request.
*/
type RetrieveAssetsParams struct {

	/* ChannelID.

	   Channel ID
	*/
	ChannelID string

	/* RepoID.

	   Repository ID
	*/
	RepoID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the retrieve assets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RetrieveAssetsParams) WithDefaults() *RetrieveAssetsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the retrieve assets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RetrieveAssetsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the retrieve assets params
func (o *RetrieveAssetsParams) WithTimeout(timeout time.Duration) *RetrieveAssetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the retrieve assets params
func (o *RetrieveAssetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the retrieve assets params
func (o *RetrieveAssetsParams) WithContext(ctx context.Context) *RetrieveAssetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the retrieve assets params
func (o *RetrieveAssetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the retrieve assets params
func (o *RetrieveAssetsParams) WithHTTPClient(client *http.Client) *RetrieveAssetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the retrieve assets params
func (o *RetrieveAssetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChannelID adds the channelID to the retrieve assets params
func (o *RetrieveAssetsParams) WithChannelID(channelID string) *RetrieveAssetsParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the retrieve assets params
func (o *RetrieveAssetsParams) SetChannelID(channelID string) {
	o.ChannelID = channelID
}

// WithRepoID adds the repoID to the retrieve assets params
func (o *RetrieveAssetsParams) WithRepoID(repoID string) *RetrieveAssetsParams {
	o.SetRepoID(repoID)
	return o
}

// SetRepoID adds the repoId to the retrieve assets params
func (o *RetrieveAssetsParams) SetRepoID(repoID string) {
	o.RepoID = repoID
}

// WriteToRequest writes these params to a swagger request
func (o *RetrieveAssetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param channelID
	if err := r.SetPathParam("channelID", o.ChannelID); err != nil {
		return err
	}

	// path param repoID
	if err := r.SetPathParam("repoID", o.RepoID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
