// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RetrieveAssetsReader is a Reader for the RetrieveAssets structure.
type RetrieveAssetsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RetrieveAssetsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRetrieveAssetsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewRetrieveAssetsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 502:
		result := NewRetrieveAssetsBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRetrieveAssetsOK creates a RetrieveAssetsOK with default headers values
func NewRetrieveAssetsOK() *RetrieveAssetsOK {
	return &RetrieveAssetsOK{}
}

/* RetrieveAssetsOK describes a response with status code 200, with default header values.

Array of asset ids have been retrieved and are in the body
*/
type RetrieveAssetsOK struct {
}

func (o *RetrieveAssetsOK) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan/{channelID}/asset][%d] retrieveAssetsOK ", 200)
}

func (o *RetrieveAssetsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRetrieveAssetsNotFound creates a RetrieveAssetsNotFound with default headers values
func NewRetrieveAssetsNotFound() *RetrieveAssetsNotFound {
	return &RetrieveAssetsNotFound{}
}

/* RetrieveAssetsNotFound describes a response with status code 404, with default header values.

No channel, repository or asset found for that URI
*/
type RetrieveAssetsNotFound struct {
}

func (o *RetrieveAssetsNotFound) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan/{channelID}/asset][%d] retrieveAssetsNotFound ", 404)
}

func (o *RetrieveAssetsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRetrieveAssetsBadGateway creates a RetrieveAssetsBadGateway with default headers values
func NewRetrieveAssetsBadGateway() *RetrieveAssetsBadGateway {
	return &RetrieveAssetsBadGateway{}
}

/* RetrieveAssetsBadGateway describes a response with status code 502, with default header values.

Error on repository agent
*/
type RetrieveAssetsBadGateway struct {
}

func (o *RetrieveAssetsBadGateway) Error() string {
	return fmt.Sprintf("[GET /repo/{repoID}/chan/{channelID}/asset][%d] retrieveAssetsBadGateway ", 502)
}

func (o *RetrieveAssetsBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
