// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRetrieveAssetParams creates a new RetrieveAssetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRetrieveAssetParams() *RetrieveAssetParams {
	return &RetrieveAssetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRetrieveAssetParamsWithTimeout creates a new RetrieveAssetParams object
// with the ability to set a timeout on a request.
func NewRetrieveAssetParamsWithTimeout(timeout time.Duration) *RetrieveAssetParams {
	return &RetrieveAssetParams{
		timeout: timeout,
	}
}

// NewRetrieveAssetParamsWithContext creates a new RetrieveAssetParams object
// with the ability to set a context for a request.
func NewRetrieveAssetParamsWithContext(ctx context.Context) *RetrieveAssetParams {
	return &RetrieveAssetParams{
		Context: ctx,
	}
}

// NewRetrieveAssetParamsWithHTTPClient creates a new RetrieveAssetParams object
// with the ability to set a custom HTTPClient for a request.
func NewRetrieveAssetParamsWithHTTPClient(client *http.Client) *RetrieveAssetParams {
	return &RetrieveAssetParams{
		HTTPClient: client,
	}
}

/* RetrieveAssetParams contains all the parameters to send to the API endpoint
   for the retrieve asset operation.

   Typically these are written to a http.Request.
*/
type RetrieveAssetParams struct {

	/* AssetID.

	   Asset ID
	*/
	AssetID string

	/* ChannelID.

	   Channel ID
	*/
	ChannelID string

	/* RepoID.

	   Repository ID
	*/
	RepoID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the retrieve asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RetrieveAssetParams) WithDefaults() *RetrieveAssetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the retrieve asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RetrieveAssetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the retrieve asset params
func (o *RetrieveAssetParams) WithTimeout(timeout time.Duration) *RetrieveAssetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the retrieve asset params
func (o *RetrieveAssetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the retrieve asset params
func (o *RetrieveAssetParams) WithContext(ctx context.Context) *RetrieveAssetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the retrieve asset params
func (o *RetrieveAssetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the retrieve asset params
func (o *RetrieveAssetParams) WithHTTPClient(client *http.Client) *RetrieveAssetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the retrieve asset params
func (o *RetrieveAssetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAssetID adds the assetID to the retrieve asset params
func (o *RetrieveAssetParams) WithAssetID(assetID string) *RetrieveAssetParams {
	o.SetAssetID(assetID)
	return o
}

// SetAssetID adds the assetId to the retrieve asset params
func (o *RetrieveAssetParams) SetAssetID(assetID string) {
	o.AssetID = assetID
}

// WithChannelID adds the channelID to the retrieve asset params
func (o *RetrieveAssetParams) WithChannelID(channelID string) *RetrieveAssetParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the retrieve asset params
func (o *RetrieveAssetParams) SetChannelID(channelID string) {
	o.ChannelID = channelID
}

// WithRepoID adds the repoID to the retrieve asset params
func (o *RetrieveAssetParams) WithRepoID(repoID string) *RetrieveAssetParams {
	o.SetRepoID(repoID)
	return o
}

// SetRepoID adds the repoId to the retrieve asset params
func (o *RetrieveAssetParams) SetRepoID(repoID string) {
	o.RepoID = repoID
}

// WriteToRequest writes these params to a swagger request
func (o *RetrieveAssetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param assetID
	if err := r.SetPathParam("assetID", o.AssetID); err != nil {
		return err
	}

	// path param channelID
	if err := r.SetPathParam("channelID", o.ChannelID); err != nil {
		return err
	}

	// path param repoID
	if err := r.SetPathParam("repoID", o.RepoID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
