// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"dbom-grafeas/dbom/models"
)

// NewTransferAssetParams creates a new TransferAssetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTransferAssetParams() *TransferAssetParams {
	return &TransferAssetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTransferAssetParamsWithTimeout creates a new TransferAssetParams object
// with the ability to set a timeout on a request.
func NewTransferAssetParamsWithTimeout(timeout time.Duration) *TransferAssetParams {
	return &TransferAssetParams{
		timeout: timeout,
	}
}

// NewTransferAssetParamsWithContext creates a new TransferAssetParams object
// with the ability to set a context for a request.
func NewTransferAssetParamsWithContext(ctx context.Context) *TransferAssetParams {
	return &TransferAssetParams{
		Context: ctx,
	}
}

// NewTransferAssetParamsWithHTTPClient creates a new TransferAssetParams object
// with the ability to set a custom HTTPClient for a request.
func NewTransferAssetParamsWithHTTPClient(client *http.Client) *TransferAssetParams {
	return &TransferAssetParams{
		HTTPClient: client,
	}
}

/* TransferAssetParams contains all the parameters to send to the API endpoint
   for the transfer asset operation.

   Typically these are written to a http.Request.
*/
type TransferAssetParams struct {

	// Body.
	Body *models.TransferAssetRequest

	/* AssetID.

	   Asset ID
	*/
	AssetID string

	/* ChannelID.

	   Channel ID
	*/
	ChannelID string

	/* RepoID.

	   Repository ID
	*/
	RepoID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the transfer asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TransferAssetParams) WithDefaults() *TransferAssetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the transfer asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TransferAssetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the transfer asset params
func (o *TransferAssetParams) WithTimeout(timeout time.Duration) *TransferAssetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the transfer asset params
func (o *TransferAssetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the transfer asset params
func (o *TransferAssetParams) WithContext(ctx context.Context) *TransferAssetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the transfer asset params
func (o *TransferAssetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the transfer asset params
func (o *TransferAssetParams) WithHTTPClient(client *http.Client) *TransferAssetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the transfer asset params
func (o *TransferAssetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the transfer asset params
func (o *TransferAssetParams) WithBody(body *models.TransferAssetRequest) *TransferAssetParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the transfer asset params
func (o *TransferAssetParams) SetBody(body *models.TransferAssetRequest) {
	o.Body = body
}

// WithAssetID adds the assetID to the transfer asset params
func (o *TransferAssetParams) WithAssetID(assetID string) *TransferAssetParams {
	o.SetAssetID(assetID)
	return o
}

// SetAssetID adds the assetId to the transfer asset params
func (o *TransferAssetParams) SetAssetID(assetID string) {
	o.AssetID = assetID
}

// WithChannelID adds the channelID to the transfer asset params
func (o *TransferAssetParams) WithChannelID(channelID string) *TransferAssetParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the transfer asset params
func (o *TransferAssetParams) SetChannelID(channelID string) {
	o.ChannelID = channelID
}

// WithRepoID adds the repoID to the transfer asset params
func (o *TransferAssetParams) WithRepoID(repoID string) *TransferAssetParams {
	o.SetRepoID(repoID)
	return o
}

// SetRepoID adds the repoId to the transfer asset params
func (o *TransferAssetParams) SetRepoID(repoID string) {
	o.RepoID = repoID
}

// WriteToRequest writes these params to a swagger request
func (o *TransferAssetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param assetID
	if err := r.SetPathParam("assetID", o.AssetID); err != nil {
		return err
	}

	// path param channelID
	if err := r.SetPathParam("channelID", o.ChannelID); err != nil {
		return err
	}

	// path param repoID
	if err := r.SetPathParam("repoID", o.RepoID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
