// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// TransferAssetReader is a Reader for the TransferAsset structure.
type TransferAssetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TransferAssetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTransferAssetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewTransferAssetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewTransferAssetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewTransferAssetConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 502:
		result := NewTransferAssetBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTransferAssetOK creates a TransferAssetOK with default headers values
func NewTransferAssetOK() *TransferAssetOK {
	return &TransferAssetOK{}
}

/* TransferAssetOK describes a response with status code 200, with default header values.

Asset was successfully transferred to the given repository details in the request body
*/
type TransferAssetOK struct {
}

func (o *TransferAssetOK) Error() string {
	return fmt.Sprintf("[POST /repo/{repoID}/chan/{channelID}/asset/{assetID}/transfer][%d] transferAssetOK ", 200)
}

func (o *TransferAssetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewTransferAssetBadRequest creates a TransferAssetBadRequest with default headers values
func NewTransferAssetBadRequest() *TransferAssetBadRequest {
	return &TransferAssetBadRequest{}
}

/* TransferAssetBadRequest describes a response with status code 400, with default header values.

Expected schema for an asset transfer was not matched
*/
type TransferAssetBadRequest struct {
}

func (o *TransferAssetBadRequest) Error() string {
	return fmt.Sprintf("[POST /repo/{repoID}/chan/{channelID}/asset/{assetID}/transfer][%d] transferAssetBadRequest ", 400)
}

func (o *TransferAssetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewTransferAssetNotFound creates a TransferAssetNotFound with default headers values
func NewTransferAssetNotFound() *TransferAssetNotFound {
	return &TransferAssetNotFound{}
}

/* TransferAssetNotFound describes a response with status code 404, with default header values.

No channel or repository found for that URI
*/
type TransferAssetNotFound struct {
}

func (o *TransferAssetNotFound) Error() string {
	return fmt.Sprintf("[POST /repo/{repoID}/chan/{channelID}/asset/{assetID}/transfer][%d] transferAssetNotFound ", 404)
}

func (o *TransferAssetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewTransferAssetConflict creates a TransferAssetConflict with default headers values
func NewTransferAssetConflict() *TransferAssetConflict {
	return &TransferAssetConflict{}
}

/* TransferAssetConflict describes a response with status code 409, with default header values.

Destination asset already exists
*/
type TransferAssetConflict struct {
}

func (o *TransferAssetConflict) Error() string {
	return fmt.Sprintf("[POST /repo/{repoID}/chan/{channelID}/asset/{assetID}/transfer][%d] transferAssetConflict ", 409)
}

func (o *TransferAssetConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewTransferAssetBadGateway creates a TransferAssetBadGateway with default headers values
func NewTransferAssetBadGateway() *TransferAssetBadGateway {
	return &TransferAssetBadGateway{}
}

/* TransferAssetBadGateway describes a response with status code 502, with default header values.

Error on repository agent
*/
type TransferAssetBadGateway struct {
}

func (o *TransferAssetBadGateway) Error() string {
	return fmt.Sprintf("[POST /repo/{repoID}/chan/{channelID}/asset/{assetID}/transfer][%d] transferAssetBadGateway ", 502)
}

func (o *TransferAssetBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
