// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"dbom-grafeas/dbom/models"
)

// NewUpdateAssetParams creates a new UpdateAssetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateAssetParams() *UpdateAssetParams {
	return &UpdateAssetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAssetParamsWithTimeout creates a new UpdateAssetParams object
// with the ability to set a timeout on a request.
func NewUpdateAssetParamsWithTimeout(timeout time.Duration) *UpdateAssetParams {
	return &UpdateAssetParams{
		timeout: timeout,
	}
}

// NewUpdateAssetParamsWithContext creates a new UpdateAssetParams object
// with the ability to set a context for a request.
func NewUpdateAssetParamsWithContext(ctx context.Context) *UpdateAssetParams {
	return &UpdateAssetParams{
		Context: ctx,
	}
}

// NewUpdateAssetParamsWithHTTPClient creates a new UpdateAssetParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateAssetParamsWithHTTPClient(client *http.Client) *UpdateAssetParams {
	return &UpdateAssetParams{
		HTTPClient: client,
	}
}

/* UpdateAssetParams contains all the parameters to send to the API endpoint
   for the update asset operation.

   Typically these are written to a http.Request.
*/
type UpdateAssetParams struct {

	// Body.
	Body *models.AssetDefinition

	/* AssetID.

	   Asset ID
	*/
	AssetID string

	/* ChannelID.

	   Channel ID
	*/
	ChannelID string

	/* RepoID.

	   Repository ID
	*/
	RepoID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateAssetParams) WithDefaults() *UpdateAssetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateAssetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update asset params
func (o *UpdateAssetParams) WithTimeout(timeout time.Duration) *UpdateAssetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update asset params
func (o *UpdateAssetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update asset params
func (o *UpdateAssetParams) WithContext(ctx context.Context) *UpdateAssetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update asset params
func (o *UpdateAssetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update asset params
func (o *UpdateAssetParams) WithHTTPClient(client *http.Client) *UpdateAssetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update asset params
func (o *UpdateAssetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update asset params
func (o *UpdateAssetParams) WithBody(body *models.AssetDefinition) *UpdateAssetParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update asset params
func (o *UpdateAssetParams) SetBody(body *models.AssetDefinition) {
	o.Body = body
}

// WithAssetID adds the assetID to the update asset params
func (o *UpdateAssetParams) WithAssetID(assetID string) *UpdateAssetParams {
	o.SetAssetID(assetID)
	return o
}

// SetAssetID adds the assetId to the update asset params
func (o *UpdateAssetParams) SetAssetID(assetID string) {
	o.AssetID = assetID
}

// WithChannelID adds the channelID to the update asset params
func (o *UpdateAssetParams) WithChannelID(channelID string) *UpdateAssetParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the update asset params
func (o *UpdateAssetParams) SetChannelID(channelID string) {
	o.ChannelID = channelID
}

// WithRepoID adds the repoID to the update asset params
func (o *UpdateAssetParams) WithRepoID(repoID string) *UpdateAssetParams {
	o.SetRepoID(repoID)
	return o
}

// SetRepoID adds the repoId to the update asset params
func (o *UpdateAssetParams) SetRepoID(repoID string) {
	o.RepoID = repoID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAssetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param assetID
	if err := r.SetPathParam("assetID", o.AssetID); err != nil {
		return err
	}

	// path param channelID
	if err := r.SetPathParam("channelID", o.ChannelID); err != nil {
		return err
	}

	// path param repoID
	if err := r.SetPathParam("repoID", o.RepoID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
