// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewValidateAssetParams creates a new ValidateAssetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewValidateAssetParams() *ValidateAssetParams {
	return &ValidateAssetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewValidateAssetParamsWithTimeout creates a new ValidateAssetParams object
// with the ability to set a timeout on a request.
func NewValidateAssetParamsWithTimeout(timeout time.Duration) *ValidateAssetParams {
	return &ValidateAssetParams{
		timeout: timeout,
	}
}

// NewValidateAssetParamsWithContext creates a new ValidateAssetParams object
// with the ability to set a context for a request.
func NewValidateAssetParamsWithContext(ctx context.Context) *ValidateAssetParams {
	return &ValidateAssetParams{
		Context: ctx,
	}
}

// NewValidateAssetParamsWithHTTPClient creates a new ValidateAssetParams object
// with the ability to set a custom HTTPClient for a request.
func NewValidateAssetParamsWithHTTPClient(client *http.Client) *ValidateAssetParams {
	return &ValidateAssetParams{
		HTTPClient: client,
	}
}

/* ValidateAssetParams contains all the parameters to send to the API endpoint
   for the validate asset operation.

   Typically these are written to a http.Request.
*/
type ValidateAssetParams struct {

	/* AssetID.

	   Asset ID
	*/
	AssetID string

	/* ChannelID.

	   Channel ID
	*/
	ChannelID string

	/* RepoID.

	   Repository ID
	*/
	RepoID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the validate asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ValidateAssetParams) WithDefaults() *ValidateAssetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the validate asset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ValidateAssetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the validate asset params
func (o *ValidateAssetParams) WithTimeout(timeout time.Duration) *ValidateAssetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the validate asset params
func (o *ValidateAssetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the validate asset params
func (o *ValidateAssetParams) WithContext(ctx context.Context) *ValidateAssetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the validate asset params
func (o *ValidateAssetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the validate asset params
func (o *ValidateAssetParams) WithHTTPClient(client *http.Client) *ValidateAssetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the validate asset params
func (o *ValidateAssetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAssetID adds the assetID to the validate asset params
func (o *ValidateAssetParams) WithAssetID(assetID string) *ValidateAssetParams {
	o.SetAssetID(assetID)
	return o
}

// SetAssetID adds the assetId to the validate asset params
func (o *ValidateAssetParams) SetAssetID(assetID string) {
	o.AssetID = assetID
}

// WithChannelID adds the channelID to the validate asset params
func (o *ValidateAssetParams) WithChannelID(channelID string) *ValidateAssetParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the validate asset params
func (o *ValidateAssetParams) SetChannelID(channelID string) {
	o.ChannelID = channelID
}

// WithRepoID adds the repoID to the validate asset params
func (o *ValidateAssetParams) WithRepoID(repoID string) *ValidateAssetParams {
	o.SetRepoID(repoID)
	return o
}

// SetRepoID adds the repoId to the validate asset params
func (o *ValidateAssetParams) SetRepoID(repoID string) {
	o.RepoID = repoID
}

// WriteToRequest writes these params to a swagger request
func (o *ValidateAssetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param assetID
	if err := r.SetPathParam("assetID", o.AssetID); err != nil {
		return err
	}

	// path param channelID
	if err := r.SetPathParam("channelID", o.ChannelID); err != nil {
		return err
	}

	// path param repoID
	if err := r.SetPathParam("repoID", o.RepoID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
